# This values for https://github.com/zhilyaev/uni-chart
# $ helm upgrade -i gcp-sa-exporter -n gcp-sa-exporter oci://ghcr.io/zhilyaev/uni -f values.yaml

envs:
  GCP_SA_EXPORTER_PARENT_ID: "<if you need scrape folder>"

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: zhilyaev/gcp-serviceaccounts-exporter
  tag: 0.2.4


ingressesGeneral:
  ingressClassName: nginx
  serviceName: &port 8080
  servicePort: *port


servicesGeneral:
  ports:
    - name: &portName http

services:
  *port: {}

deploymentsGeneral:
  livenessProbe:
    httpGet:
      path: /metrics
      port: *port
    initialDelaySeconds: 60
    periodSeconds: 3
    timeoutSeconds: 3
  ports:
    - name: *portName
      containerPort: *port
  envConfigmaps:
    - envs


deployments:
  app:
    replicas: 1
    envConfigmaps:
      - envs
    containers:
      - name: app
        args: ["run"]
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 200Mi
            cpu: 550m

serviceAccountName: gcp-sa-exporter

serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: gcp-sa-exporter@<your-project>.iam.gserviceaccount.com


serviceMonitors:
  app:
    endpoints:
      - interval: 30s
        path: /metrics
        port: *portName

alerts:
  gcp-sa-exporter:
    groups:
      - name: GCPExpiredServiceAccounts
        rules:
          - alert: GCPExpiredServiceAccounts120Days
            annotations:
              summary: Expired key {{ $labels.key }}
            expr: gcp_service_accounts_expired_keys > 120
            for: 1s
            labels:
              severity: warning
